spring.application.name=gerenciamento-lab
springdoc.swagger-ui.path=/gerenciamento-lab/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
 #springdoc.swagger-ui.enabled=true
 #springdoc.api-docs.enabled=true

spring.datasource.url=jdbc:postgresql://
spring.datasource.username=gerenciamento-lab
spring.datasource.password=aluno
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver